aygunmedia/Models/Siniflar/Admin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace aygunmedia.Models.Siniflar
{
	public class Admin
	{
        public int id { get; set; }
        public string kullaniciAdi { get; set; }
        public string sifre { get; set; }
    }
}

aygunmedia/Models/Siniflar/AnaSayfa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace aygunmedia.Models.Siniflar
{
	public class AnaSayfa
	{
        [Key]
        public int id { get; set; }
        public string profil { get; set; }
        public string isim { get; set; }
        public string unvan { get; set; }
        public string aciklama { get; set; }
        public string iletisim { get; set; }
    }
}

aygunmedia/Models/Siniflar/Context.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace aygunmedia.Models.Siniflar
{
	public class Context : DbContext
	{
        public DbSet<Admin> Admins { get; set; }
        public DbSet<AnaSayfa> AnaSayfas { get; set; }
        public DbSet<ikonlar> ikonlars { get; set; }
        public DbSet<Skill> Skills { get; set; }
    }
}

aygunmedia/Models/Siniflar/Skill.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace aygunmedia.Models.Siniflar
{
    public class Skill
    {
        public int Id { get; set; } // Yetenek için benzersiz ID
        public string yetenekAd { get; set; } // Yetenek adı
        public int yuzde { get; set; } // Yetenek yüzdesi
    }
}

aygunmedia/Models/Siniflar/ikonlar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace aygunmedia.Models.Siniflar
{
	public class ikonlar
	{
        [Key]
        public int id { get; set; }
        public string ikon { get; set; }
        public string link { get; set; }
    }
}

aygunmedia/Controllers/AdminController.cs
using aygunmedia.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace aygunmedia.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        Context c = new Context();
        [Authorize]
        public ActionResult Index()
        {
            var deger = c.AnaSayfas.ToList();
            return View(deger);
        }
        public ActionResult AnaSayfaGetir(int id)
        {
            var ag = c.AnaSayfas.Find(id);
            return View("AnaSayfaGetir", ag);
        }
        public ActionResult AnaSayfaGuncelle(AnaSayfa x)
        {
            var ag = c.AnaSayfas.Find(x.id);
            ag.profil = x.profil;
            ag.isim = x.isim;
            ag.unvan = x.unvan;
            ag.aciklama = x.aciklama;
            ag.iletisim = x.iletisim;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ikonListesi()
        {
            var deger = c.ikonlars.ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult YeniIkon()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniIkon(ikonlar p)
        {
            c.ikonlars.Add(p);
            c.SaveChanges();
            return RedirectToAction("ikonListesi");
        }
        public ActionResult ikonGetir(int id)
        {
            var ig = c.ikonlars.Find(id);
            return View("ikonGetir", ig);
        }
        public ActionResult ikonGuncelle(ikonlar x)
        {
            var ig = c.ikonlars.Find(x.id);
            ig.ikon = x.ikon;
            ig.link = x.link;
            c.SaveChanges();
            return RedirectToAction("ikonListesi");
        }
        public ActionResult ikonSil(int id)
        {
            var sl = c.ikonlars.Find(id);
            c.ikonlars.Remove(sl);
            c.SaveChanges();
            return RedirectToAction("ikonListesi");
        }
        // skills işlemleri ------------------------------
        public ActionResult SkillListesi()
        {
            var deger = c.Skills.ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult YeniSkill()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniSkill(Skill p)
        {
            c.Skills.Add(p);
            c.SaveChanges();
            return RedirectToAction("SkillListesi");
        }
        public ActionResult SkillGetir(int Id)
        {
            var ig = c.Skills.Find(Id);
            return View("SkillGetir", ig);
        }
        public ActionResult SkillGuncelle(Skill x)
        {
            var ig = c.Skills.Find(x.Id);
            ig.yetenekAd = x.yetenekAd;
            ig.yuzde = x.yuzde;
            c.SaveChanges();
            return RedirectToAction("SkillListesi");
        }
        public ActionResult SkillSil(int Id)
        {
            var sl = c.Skills.Find(Id);
            c.Skills.Remove(sl);
            c.SaveChanges();
            return RedirectToAction("SkillListesi");
        }
    }
}

aygunmedia/Controllers/AnaSayfaController.cs
using aygunmedia.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace aygunmedia.Controllers
{
    public class AnaSayfaController : Controller
    {
        // GET: AnaSayfa
        Context c = new Context();
        public ActionResult Index()
        {
            var deger = c.AnaSayfas.ToList();
            return View(deger);
        }

        public PartialViewResult ikonlar()
        {
            var deger = c.ikonlars.ToList();
            return PartialView(deger);
        }
        public PartialViewResult Skill()
        {
            var deger = c.Skills.ToList();
            return PartialView(deger);
        }
    }
}

aygunmedia/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace aygunmedia.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

aygunmedia/Controllers/LoginController.cs
using aygunmedia.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace aygunmedia.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        Context c = new Context();
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Admin ad)
        {
            var bilgiler = c.Admins.FirstOrDefault(x => x.kullaniciAdi == ad.kullaniciAdi && x.sifre == ad.sifre);
            if (bilgiler != null)
            {
                FormsAuthentication.SetAuthCookie(bilgiler.kullaniciAdi, false);
                Session["kullaniciAdi"] = bilgiler.kullaniciAdi.ToString();
                return RedirectToAction("Index", "Admin");
            }
            else
            {
                return View();
            }
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Login");
        }

    }
}

aygunmedia/Views/Admin/AnaSayfaGetir.cshtml
@model aygunmedia.Models.Siniflar.AnaSayfa
@{
    ViewBag.Title = "AnaSayfaGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2 class="mt-4">Ana Sayfa Güncelle</h2>
<hr />

@using (Html.BeginForm("AnaSayfaGuncelle", "Admin", FormMethod.Post))
{
    @Html.LabelFor(x => x.id)
    @Html.TextBoxFor(x => x.id, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.isim)
    @Html.TextBoxFor(x => x.isim, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.profil)
    @Html.TextBoxFor(x => x.profil, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.aciklama)
    @Html.TextAreaFor(x => x.aciklama, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.unvan)
    @Html.TextBoxFor(x => x.unvan, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.iletisim)
    @Html.TextBoxFor(x => x.iletisim, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">AnaSayfa Güncelle</button>
}

aygunmedia/Views/Admin/Index.cshtml
@using aygunmedia.Models.Siniflar;
@model List<AnaSayfa>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- ANA SAYFA ADMİN CONTROL -->
<h2 class="mb-4">Ana Sayfa</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>İsim</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.isim</td>
            <td><a href="/Admin/AnaSayfaGetir/@x.id" class="btn btn-primary">Güncelle</a></td>
        </tr>
    }
</table>

aygunmedia/Views/Admin/SkillGetir.cshtml
@model aygunmedia.Models.Siniflar.Skill
@{
    ViewBag.Title = "SkillGetir";
}

<h2>Skill Güncelle</h2>
<br />
@using (Html.BeginForm("SkillGuncelle", "Admin", FormMethod.Post))
{
    @Html.LabelFor(x => x.Id)
    @Html.TextBoxFor(x => x.Id, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.yetenekAd)
    @Html.TextBoxFor(x => x.yetenekAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.yuzde)
    @Html.TextBoxFor(x => x.yuzde, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Skill Güncelle</button>
}

aygunmedia/Views/Admin/SkillListesi.cshtml
@using aygunmedia.Models.Siniflar
@model List<Skill>
@{
    ViewBag.Title = "SkillListesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2 class="mb-4">Skill Sayfası</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Skill</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Id</td>
            <td>@x.yetenekAd</td>
            <td><a href="/Admin/SkillGetir/@x.Id" class="btn btn-primary">Güncelle</a></td>
            <td><a href="/Admin/SkillSil/@x.Id" class="btn btn-danger">Sil</a></td>
        </tr>
    }
</table>
<a href="/Admin/YeniSkill/" class="btn btn-primary">Yeni Skill Ekle</a>

aygunmedia/Views/Admin/YeniIkon.cshtml
@model aygunmedia.Models.Siniflar.ikonlar
@{
    ViewBag.Title = "YeniIkon";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Ikon Ekle</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.ikon)
    @Html.TextBoxFor(x => x.ikon, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.link)
    @Html.TextBoxFor(x => x.link, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">İkon Ekle</button>
</form>

aygunmedia/Views/Admin/YeniSkill.cshtml
@model aygunmedia.Models.Siniflar.Skill
@{
    ViewBag.Title = "YeniSkill";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yeni Skill Ekle</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.yetenekAd)
    @Html.TextBoxFor(x => x.yetenekAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.yuzde)
    @Html.TextBoxFor(x => x.yuzde, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Skill Ekle</button>
</form>

aygunmedia/Views/Admin/ikonGetir.cshtml
@model aygunmedia.Models.Siniflar.ikonlar
@{
    ViewBag.Title = "ikonGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>İkon Güncelle</h2>
<br />
@using (Html.BeginForm("ikonGuncelle", "Admin", FormMethod.Post))
{
    @Html.LabelFor(x => x.id)
    @Html.TextBoxFor(x => x.id, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.ikon)
    @Html.TextBoxFor(x => x.ikon, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.link)
    @Html.TextBoxFor(x => x.link, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">İkon Güncelle</button>
}

aygunmedia/Views/Admin/ikonListesi.cshtml
@using aygunmedia.Models.Siniflar
@model List<ikonlar>
@{
    ViewBag.Title = "ikonListesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2 class="mb-4">İkon Sayfası</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>ikon</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td><i class="@x.ikon"></i></td>
            <td><a href="/Admin/ikonGetir/@x.id" class="btn btn-primary">Güncelle</a></td>
            <td><a href="/Admin/ikonSil/@x.id" class="btn btn-danger">Sil</a></td>
        </tr>
    }
</table>
<a href="/Admin/YeniIkon/" class="btn btn-primary">Yeni İkon Ekle</a>

aygunmedia/Views/AnaSayfa/Index.cshtml
@using aygunmedia.Models.Siniflar
@model List<AnaSayfa>
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kişisel Web Sitesi</title>
    <link rel="stylesheet" href="~/anasayfa-tamplate/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <style>
        #particles-js {
    position: absolute;
    width: 100%;
    height: 99%;
    top: 0;
    left: 0;
    z-index: -1;
    pointer-events: all;
}
    .loader-container {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: radial-gradient(circle, #4a4a4a, #000000);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 9999; /* Diğer içeriklerin üstünde */
    transition: opacity 1s ease; /* Geçiş efekti */
}

.loader {
    border: 8px solid #f3f3f3; /* Açık gri */
    border-top: 8px solid #3498db; /* Mavi */
    border-radius: 50%;
    width: 60px;
    height: 60px;
    animation: spin 1s linear infinite;
}

@@keyframes spin {
    0% {
        transform: rotate(0deg);
    }

    100% {
        transform: rotate(360deg);
    }
}
    </style>
</head>
<body>
    <!-- loader -->
    <div class="loader-container" id="loader">
        <div class="loader"></div>
    </div>
    <!-- context -->
    <div class="contentt" id="contentt">
        <div class="center">
            <div class="avatar">
                @foreach (var x in Model)
                {
                    <img src="@x.profil">
                }
            </div>
            <div class="content">
                @foreach (var x in Model)
                {
                    <h1>@x.isim</h1>
                    <h2>@x.unvan</h2>
                    <p>@x.aciklama</p>
                    <h3>@x.iletisim</h3>
                }
            </div>
            @Html.Action("ikonlar", "AnaSayfa")
        </div>
        @Html.Action("skill", "AnaSayfa")
    </div>
    <div id="particles-js"></div>
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script>
        window.onload = function () {
            setTimeout(() => {
                document.getElementById("loader").style.opacity = "0";
                setTimeout(() => {
                    document.getElementById("loader").style.display = "none";
                    document.getElementById("content").style.display = "block"; // İçeriği göster
                }, 500);
            }, 3000); // 3 saniye bekle
        };
    </script>
    <script>
        particlesJS('particles-js', {
            particles: {
                number: { value: 100, density: { enable: true, value_area: 800 } },
                color: { value: "#ffffff" },
                shape: { type: "circle" },
                opacity: { value: 0.5, random: false },
                size: { value: 4, random: true },
                move: { enable: true, speed: 2, direction: "none" }
            },
            interactivity: {
                events: { onhover: { enable: true, mode: "repulse" } },
                modes: { repulse: { distance: 100, duration: 1 } }
            }
        });
    </script>
</body>
</html>

aygunmedia/Views/AnaSayfa/Skill.cshtml
@using aygunmedia.Models.Siniflar
@model List<Skill>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Skill</title>
    <style>
        /* Skill Sayfası için Stiller */
        .skills-container {
            z-index: 9;
            width: 45%;
            min-width: 350px;
            background-color: rgba(255,255,255,0.09);
            height: 550px;
            border-radius: 50px;
            padding: 30px;
        }

        .my-skills {
            margin-top: 30px;
        }

        .skill {
            margin: 10px 0;
        }

            .skill span {
                display: block;
                margin-bottom: 5px;
                color: #fff;
            }

        .skill-bar {
            height: 10px;
            background-color: #3498db;
            border-radius: 5px;
            transition: width 0.5s ease;
        }
    </style>
</head>
<body>
    <div class="skills-container">
        <div class="my-skills">
            <h2>Yeteneklerim</h2>
            @foreach (var x in Model)
            {
                <div class="skill">
                    <span>@x.yetenekAd</span>
                    <div class="skill-bar" style=" width: @x.yuzde%;"></div>
                </div>
            }
        </div>
    </div>
</body>
</html>

aygunmedia/Views/AnaSayfa/ikonlar.cshtml
@using aygunmedia.Models.Siniflar
@model List<ikonlar>

<div class="social">
    @foreach (var x in Model)
    {
        <a target="_blank" href="@x.link"><i class="@x.ikon"></i></a>
    }
</div>

aygunmedia/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel Login</title>
    <link rel="stylesheet" href="~/adminlogin-tamplate/css/style.css">
</head>
<body>

    <div class="container">
        <div class="contact-form">
            <img src="~/adminlogin-tamplate/img/admin.jpg" class="admin-img">
            <h2>Admin Login</h2>
            @using (Html.BeginForm("Index", "Login", FormMethod.Post))
            {
                <div class="txtb">
                    <input type="text" name="kullaniciAdi" placeholder="Username">
                </div>
                <div class="txtb">
                    <input type="password" name="sifre" placeholder="Password">
                </div>
                <input type="submit" class="logbtn" value="Login">
            }
        </div>
    </div>

</body>
</html>

aygunmedia/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" />
    <title> Admin Panel</title>
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
    <style>
        /* Sidebar */
        .sidebar {
            width: 250px;
            height: 100vh;
            background-color: #2c3e50;
            color: white;
            padding-top: 20px;
            position: fixed;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

            .sidebar h2 {
                text-align: center;
                margin-bottom: 20px;
                font-size: 20px;
            }

        .menu {
            list-style: none;
            padding: 0;
        }

            .menu li {
                margin-bottom: 10px;
            }

            .menu a {
                display: flex;
                align-items: center;
                color: white;
                text-decoration: none;
                padding: 12px 20px;
                font-size: 16px;
                border-radius: 5px;
                transition: background 0.3s ease;
            }

                .menu a:hover {
                    background-color: #34495e;
                }

            .menu i {
                width: 24px;
                text-align: center;
                margin-right: 12px;
                font-size: 18px;
            }

        .admin-info {
            text-align: center;
            padding-top: 30px;
            padding-bottom: 15px;
            padding-left: 15px;
            padding-right: 15px;
            border-top: 1px solid #555;
        }

            .admin-info img {
                width: 70px;
                height: 62px;
                margin-bottom: 10px;
            }

            .admin-info p {
                margin: 5px 0;
            }

            .admin-info .time {
                font-size: 14px;
                font-weight: bold;
                color: #f1c40f;
            }

        body {
            margin: 0;
            font-family: Arial, sans-serif;
        }

        .sidebar {
            width: 250px;
            height: 100vh;
            background-color: #2c3e50;
            color: white;
            position: fixed;
            left: 0;
            top: 0;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding-top: 20px;
            transition: transform 0.3s ease;
        }

        .menu {
            list-style: none;
            padding: 0;
        }

            .menu li {
                margin-bottom: 10px;
            }

            .menu a {
                display: flex;
                align-items: center;
                color: white;
                text-decoration: none;
                padding: 12px 20px;
                font-size: 16px;
                border-radius: 5px;
                transition: background 0.3s ease;
            }

                .menu a:hover {
                    background-color: #34495e;
                }

            .menu i {
                width: 24px;
                text-align: center;
                margin-right: 12px;
                font-size: 18px;
            }

        .admin-info {
            text-align: center;
            padding: 15px;
            border-top: 1px solid #555;
        }

            .admin-info img {
                width: 70px;
                height: 62px;
                margin-bottom: 10px;
            }

            .admin-info .time {
                font-size: 14px;
                font-weight: bold;
                color: #f1c40f;
            }

        .menu-toggle {
            display: none;
            position: absolute;
            top: 20px;
            left: 20px;
            background: #2c3e50;
            border: none;
            color: white;
            padding: 10px;
            cursor: pointer;
            border-radius: 5px;
            font-size: 18px;
        }

        .close-btn {
            display: none;
            position: absolute;
            top: 15px;
            right: 15px;
            font-size: 24px;
            color: white;
            background: none;
            border: none;
            cursor: pointer;
        }

        @@media (max-width: 1024px) {
            .menu-toggle {
                display: block;
            }

            .sidebar {
                transform: translateX(-250px);
            }

                .sidebar.open {
                    transform: translateX(0);
                }

            .close-btn {
                display: block;
            }
        }
    </style>
</head>
<body>
    <button class="menu-toggle" onclick="toggleSidebar()">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Sidebar -->
    <div class="sidebar" id="sidebar">
        <div>
            <button class="close-btn" onclick="toggleSidebar()">&times;</button>
            <h2>Admin Panel</h2>
            <ul class="menu">
                <li><a href="/Admin/Index"><i class="fa-solid fa-house"></i>Ana Sayfa</a></li>
                <li><a href="/Admin/ikonListesi"><i class="fa-solid fa-icons"></i>İkonlar</a></li>
                <li><a href="/Admin/SkillListesi"><i class="fa-solid fa-person"></i>Yetenekler</a></li>
                <li><a href="/Anasayfa/Index" target="_blank"><i class="fa-solid fa-globe"></i>Siteye Git</a></li>
                <li><a href="/Login/LogOut/"><i class="fa-solid fa-sign-out-alt"></i>Çıkış Yap</a></li>
            </ul>
        </div>

        <!-- Admin Bilgileri Kısmı -->
        <div class="admin-info">
            <img src="~/anasayfa-tamplate/falogowhite.png" alt="Admin Foto">
            <p>Hoş geldiniz, <strong>Furkan</strong></p>
            <p class="time" id="datetime"></p>
        </div>
    </div>

    <!-- Page Content -->
    <div style="margin-left:20%">

        <div class="w3-container" style="background-image: linear-gradient(120deg, #3498db, #8e44ad)">
            <h1 style="color:white">İçerik Kontrol</h1>
        </div>
        <div class="w3-container">
            @RenderBody()
        </div>
    </div>
    <script>
        function toggleSidebar() {
            document.getElementById("sidebar").classList.toggle("open");
        }
    </script>
    <script>
        function updateDateTime() {
            const now = new Date();
            const days = ["Pazar", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi"];
            const day = days[now.getDay()];
            const hours = now.getHours().toString().padStart(2, '0');
            const minutes = now.getMinutes().toString().padStart(2, '0');
            const timeString = `${hours}:${minutes} - ${day}`;
            document.getElementById("datetime").innerText = timeString;
        }

        setInterval(updateDateTime, 1000);
        updateDateTime();
    </script>
</body>
</html>

aygunmedia/Views/Shared/_Layout.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <div class="container body-content">
            @RenderBody()
            <hr />
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>